system:
  id: test
  listen: 0.0.0.0
  port: 8000
  root: /app
  salt: change-for-production

memory:
  type: redis
  model: direct
  host: localhost
  port: 6379

db:
  type: mongo
  host: localhost

# User uses cache for permissions
cache:
  type: global
  ttl: 60

auth:
  bearerTokenTTL: 3600 # default

registry:
  services:
    auth-service:
      name: Auth service
      specs:
        - /auth.yaml
      handlers:
        - /handlers

#TODO: decouple, auth should load user by default
user:
  defaultRole: member
  adminRole: admin
  passwordLength: 8
  meta:
    fname:
      mandatory: true
      message: Missing first name
    lname:
      mandatory: true
      message: Missing last name
    username:
      mandatory: false
    avatar:
      mandatory: false
