system:
  id: test
  listen: 0.0.0.0
  port: 8000
  root: /app
  salt: change-for-production

memory:
  type: redis
  model: direct
  host: localhost
  port: 6379
  name: ""
  password: ""

db:
  type: mongo
  name: ""
  user: ""
  password: ""
  host: ""

cache:
  type: global # shared
  expires: 60000 # 24h expiration

services:
  - /auth.yaml

handlers:
  - /handlers

auth:
  bearerTokenTTL: 3600 # default = 3600
