swagger: '2.0'
info:
  title: Auth service
  description: Service that authenticates users
  version: '1.0.0'
host: api.cloudfiled.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /auth/{ctx}:
    get:
      summary: Returns authorised user
      description: |
        Returns authorised user
      parameters:
        - name: ctx
          in: path
          description: Ignored
          required: true
          type: string
      tags:
        - User
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Authorises user
      description: |
        Authorises user to use the system
      parameters:
        - name: ctx
          in: path
          description: How many accounts sto skip
          required: true
          type: string
      tags:
        - User
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Product:
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
